Fixing the squeezing problem of the Selector div
charkour/react-reactions pull request #65
Opened 2021-03-17 18:13 UTC by the-wrong-guy

I changed the display from `flex `to `-webkit-inline-box`, cause it solves the squeezing problem, if you not gonna merge it them let me pass styles to it through prop

2021-03-17 18:39 UTC, charkour commented
Thanks for the PR! I'll take a look at it this weekend.

2021-03-17 18:40 UTC, charkour commented
Not sure why the build is failing, but I can look into that as well.

2021-03-17 19:12 UTC, the-wrong-guy commented
> Not sure why the build is failing, but I can look into that as well.

maybe it's with bot
And  can you please do it by today itself i need it urgently, just change the display to `-webkit-inline-box`

2021-03-17 19:39 UTC, charkour commented
If you need it urgently, I would recommend using your forked branch for now.

2021-03-17 19:40 UTC, the-wrong-guy commented
> If you need it urgently, I would recommend using your forked branch for now.

how to do that ?

2021-03-17 19:45 UTC, charkour commented
I'd recommend doing a google search. I cannot be your web-dev teacher.

2021-03-22 14:28 UTC, charkour requested changes
This PR is breaking because there are duplicate `display` keys in the counterStyle object. There are better ways to apply vendor-specific prefixes. [The `inline-box` value is also outdated](https://stackoverflow.com/a/21733092/9931154).

2021-03-22 14:30 UTC, charkour commented
If you can make changes to fix the PR, I would be happy to reevaluate it.

2021-10-03 21:14 UTC, charkour commented
Closing due to inactivity.

2021-10-03 21:14 UTC, closed without merging